# Copyright (c) 2024 Microchip Technologies
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: greenlsi
      url-base: https://github.com/greenlsi
    - name: pic64gx
      url-base: https://github.com/pic64gx
      
  projects:
    - name: zephyr
      remote: greenlsi
      revision: dev-pic64gx
      path: zephyr
      import:
        name-allowlist:
          - hal_microchip
          - open-amp
          - libmetal
          
    - name: pic64gx-rpmsg-lite
      remote: pic64gx-zephyrproject-rtos
      path: modules/lib/rpmsg-lite
      revision: 63229af4a7bd50003968062b4328163c66bf1097
      #  path-blocklist:
      #  - name: modules/hal/*
      #  - name: tools/*
